package com.vnest.txznet;

public class App {
    public static final String ANKAI_CAMERA_PKG = "com.ankai.cardvr";
    public static final String ASSISTANT_PKG = "com.google.android.googlequicksearchbox";
    public static final String AUTOAI_TV_PKG = "com.autoai.aitv";
    public static final String CSN_PKG = "com.flex.csn";
    public static final String DIALER_PKG = "com.android.dialer";
    public static final int DOWNLOAD_NOTIFICATION_ID = 10004;
    public static final String DOWNLOAD_PRIMARY_CHANNEL = "vn.autoai.android.channel.download";
    public static final int FIREBASE_NOTIFICATION_ID = 10005;
    public static final String FIREBASE_PRIMARY_CHANNEL = "vn.autoai.android.channel.firebase";
    public static final String FVSM_CAMERA_PKG = "com.fvsm.camera";
    public static final String GOOGLE_CONTACT_PKG = "com.google.android.contacts";
    public static final String GOOGLE_PLAY_PKG = "com.android.vending";
    public static final int KALDI_NOTIFICATION_ID = 10001;
    public static final String KALDI_PRIMARY_CHANNEL = "vn.autoai.android.channel.kaldi";
    public static final String MX_PLAYER_PKG = "com.mxtech.videoplayer.ad";
    public static final String MX_PLAYER_PRO_PKG = "com.mxtech.videoplayer.pro";
    public static final String NCT_PKG = "ht.nct";
    public static final String NCT_URL = "https://www.nhaccuatui.com/";
    public static final int SPEAK_NOTIFICATION_ID = 10003;
    public static final String SPEAK_PRIMARY_CHANNEL = "vn.autoai.android.channel.speak";
    public static final String SPOTIFY_PKG = "com.spotify.music";
    public static final String SPOTIFY_URL = "https://openMap.spotify.com/";
    public static final String STEELMATE_TPMS_PKG = "com.steelmate.vietnamt620";
    public static final String SYU_AV_PKG = "com.syu.av";
    public static final String SYU_BT_PKG = "com.syu.bt";
    public static final String SYU_FV_PKG = "com.syu.frontvideo";
    public static final String SYU_MUSIC_PKG = "com.syu.music";
    public static final String SYU_RADIO_PKG = "com.syu.radio";
    public static final String SYU_TPMS_PKG = "com.syt.tmps";
    public static final String SYU_VIDEO_PKG = "com.syu.video";
    public static final String TEYES_FRONT_CAMERA_PKG = "com.teyes.carkit";
    public static final String TEYES_REAR_CAMERA_PKG = "com.syu.camera360";
    public static final String TEYES_TPMS_PKG = "com.tpms3";
    public static final String TEYES_TV_PKG = "com.autoai.aitv";
    public static final String TL_TPMS_PKG = "com.tl.tpms";
    public static final int TRACK_NOTIFICATION_ID = 10002;
    public static final String TRACK_PRIMARY_CHANNEL = "vn.autoai.android.channel.track";
    public static final String YANDEX_MAP_PKG = "ru.yandex.yandexnavi";
    public static final String YOUTUBE_PKG = "com.google.android.youtube";
    public static final String YOUTUBE_VANCED_PKG = "com.vanced.android.youtube";
    public static final String ZING_MP3_PKG = "com.zing.mp3";
    public static final String ZING_MP3_URL = "https://m.mp3.zing.vn/";
}
